# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    PortFolioBundle\:
        resource: '../../src/PortFolioBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/PortFolioBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    PortFolioBundle\Controller\:
        resource: '../../src/PortFolioBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }

    app.guzzle:
        class: 'GuzzleHttp\Client'

    portfolio.github.api:
        public: true
        class: PortFolioBundle\Services\Github\Api
        arguments:
            - '@app.guzzle'
            - '%portfolio.github_token%'
            - '%portfolio.base_uri.github_api%'

    portfolio.github.event_factory:
        class: 'PortFolioBundle\Services\Github\EventFactory'
        public: true

    portfolio.github.user_activity:
        public: true
        class: PortFolioBundle\Services\Github\UserActivity
        arguments:
            - '@portfolio.github.api'
            - '%portfolio.github_user%'
            - '@portfolio.github.event_factory'